# buildspec.yml
version: 0.2

env:
  variables:
    ECR_REGISTRY: 733075603663.dkr.ecr.us-east-1.amazonaws.com
    ECR_REPOSITORY: genwarp
    IMAGE_TAG: latest
    AWS_REGION: eu-west-1

phases:
  install:
    runtime-versions:
      docker: 20

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPOSITORY .
      - docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
